base_url: "https://api.worldsacross.com/api"
timezone: "Europe/Madrid"
login_endpoint: "/auth/login"
availability_endpoint: "/auth/booking/calendar"
booking_endpoint: "/auth/booking/new-add"
list_bookings_endpoint: "/auth/booking/list"
cancel_booking_endpoint: "/auth/booking/cancel"
server_time_endpoint: "/auth/hora"
